#!/bin/sh -f
#--------------------------------------------------------------------------------------
# THE RUN FILE created by Cadence Extraction Quantus QRC UI Version 14.23-s099
#--------------------------------------------------------------------------------------

qrc  -log_file /home/saul/Assura/ASSURA_LVS/current_mirror3/qrc.alfa.log -cmd /home/saul/Assura/ASSURA_LVS/current_mirror3/qrc.alfa.ccl
