*******************************************************************************
****** FILLCAPX16 cmos_sch CORELIB  <vs>  FILLCAPX16 layout CORELIB
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(nfet) Generic                                    1       1
(pfet) Generic                                    1       1
                                             ------  ------
Total                                             2       2

Filter Statistics
=================                               Original            Filtered
Cell/Device                               schematic  layout   schematic  layout
(nfet) Generic                                    0       0           0       0
(nfet_m0) Generic                                 1       1           1       1
(pfet) Generic                                    0       0           0       0
(pfet_m0) Generic                                 1       1           1       1

Reduce Statistics
=================                               Filtered             Reduced
Cell/Device                               schematic  layout   schematic  layout
(nfet) Generic                                    0       0           0       0
(nfet_m0) Generic                                 1       1           1       1
(pfet) Generic                                    0       0           0       0
(pfet_m0) Generic                                 1       1           1       1
                                             ------  ------      ------  ------
Total                                             2       2           2       2

*******************************************************************************
****** FILLCAPX4 cmos_sch CORELIB  <vs>  FILLCAPX4 layout CORELIB
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(nfet) Generic                                    1       1
(pfet) Generic                                    1       1
                                             ------  ------
Total                                             2       2

Filter Statistics
=================                               Original            Filtered
Cell/Device                               schematic  layout   schematic  layout
(nfet) Generic                                    0       0           0       0
(nfet_m0) Generic                                 1       1           1       1
(pfet) Generic                                    0       0           0       0
(pfet_m0) Generic                                 1       1           1       1

Reduce Statistics
=================                               Filtered             Reduced
Cell/Device                               schematic  layout   schematic  layout
(nfet) Generic                                    0       0           0       0
(nfet_m0) Generic                                 1       1           1       1
(pfet) Generic                                    0       0           0       0
(pfet_m0) Generic                                 1       1           1       1
                                             ------  ------      ------  ------
Total                                             2       2           2       2

*******************************************************************************
****** FILLCAPX8 cmos_sch CORELIB  <vs>  FILLCAPX8 layout CORELIB
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(nfet) Generic                                    1       1
(pfet) Generic                                    1       1
                                             ------  ------
Total                                             2       2

Filter Statistics
=================                               Original            Filtered
Cell/Device                               schematic  layout   schematic  layout
(nfet) Generic                                    0       0           0       0
(nfet_m0) Generic                                 1       1           1       1
(pfet) Generic                                    0       0           0       0
(pfet_m0) Generic                                 1       1           1       1

Reduce Statistics
=================                               Filtered             Reduced
Cell/Device                               schematic  layout   schematic  layout
(nfet) Generic                                    0       0           0       0
(nfet_m0) Generic                                 1       1           1       1
(pfet) Generic                                    0       0           0       0
(pfet_m0) Generic                                 1       1           1       1
                                             ------  ------      ------  ------
Total                                             2       2           2       2

*******************************************************************************
****** FILLCAPX32 cmos_sch CORELIB  <vs>  FILLCAPX32 layout CORELIB
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(nfet) Generic                                    1       1
(pfet) Generic                                    1       1
                                             ------  ------
Total                                             2       2

Filter Statistics
=================                               Original            Filtered
Cell/Device                               schematic  layout   schematic  layout
(nfet) Generic                                    0       0           0       0
(nfet_m0) Generic                                 1       1           1       1
(pfet) Generic                                    0       0           0       0
(pfet_m0) Generic                                 1       1           1       1

Reduce Statistics
=================                               Filtered             Reduced
Cell/Device                               schematic  layout   schematic  layout
(nfet) Generic                                    0       0           0       0
(nfet_m0) Generic                                 1       1           1       1
(pfet) Generic                                    0       0           0       0
(pfet_m0) Generic                                 1       1           1       1
                                             ------  ------      ------  ------
Total                                             2       2           2       2

###############################################################################
###### NAND3X1 cmos_sch CORELIB  <vs>  NAND3X1 layout CORELIB
###############################################################################
###### This report is for informational purposes only. This cell
###### has been expanded because of a mismatch in reduced instance counts.
###############################################################################

Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(pfet) Generic                                    3       3
(subc) Generic                                    1       0*
(nfet) Generic                                    3       3
                                             ------  ------
Total                                             7       6

Filter Statistics
=================                               Original            Filtered
Cell/Device                               schematic  layout   schematic  layout
(nfet) Generic                                    0       0           0       0
(nfet_m0) Generic                                 3       3           3       3
(pfet) Generic                                    0       0           0       0
(pfet_m0) Generic                                 3       3           3       3
(subc, -) Generic                                 1       -*          1       -*

Reduce Statistics
=================                               Filtered             Reduced
Cell/Device                               schematic  layout   schematic  layout
(nfet) Generic                                    0       0           0       0
(nfet_m0) Generic                                 3       3           3       3
(pfet) Generic                                    0       0           0       0
(pfet_m0) Generic                                 3       3           3       3
(subc, -) Generic                                 1       -*          1       -*
                                             ------  ------      ------  ------
Total                                             7       6           7       6

###############################################################################
###### DFPX3 cmos_sch CORELIB  <vs>  DFPX3 layout CORELIB
###############################################################################
###### This report is for informational purposes only. This cell
###### has been expanded because of a mismatch in reduced instance counts.
###############################################################################

Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(subc) Generic                                    1       0*
(nfet) Generic                                   15      15
(pfet) Generic                                   15      15
                                             ------  ------
Total                                            31      30

Filter Statistics
=================                               Original            Filtered
Cell/Device                               schematic  layout   schematic  layout
(nfet) Generic                                    0       0           0       0
(nfet_m0) Generic                                15      15          15      15
(pfet) Generic                                    0       0           0       0
(pfet_m0) Generic                                15      15          15      15
(subc, -) Generic                                 1       -*          1       -*

Reduce Statistics
=================                               Filtered             Reduced
Cell/Device                               schematic  layout   schematic  layout
(nfet) Generic                                    0       0           0       0
(nfet_m0) Generic                                15      15          15      15
(pfet) Generic                                    0       0           0       0
(pfet_m0) Generic                                15      15          15      15
(subc, -) Generic                                 1       -*          1       -*
                                             ------  ------      ------  ------
Total                                            31      30          31      30

###############################################################################
###### INVXL cmos_sch CORELIB  <vs>  INVXL layout CORELIB
###############################################################################
###### This report is for informational purposes only. This cell
###### has been expanded because of a mismatch in reduced instance counts.
###############################################################################

Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(nfet) Generic                                    1       1
(subc) Generic                                    1       0*
(pfet) Generic                                    1       1
                                             ------  ------
Total                                             3       2

Filter Statistics
=================                               Original            Filtered
Cell/Device                               schematic  layout   schematic  layout
(nfet) Generic                                    0       0           0       0
(nfet_m0) Generic                                 1       1           1       1
(pfet) Generic                                    0       0           0       0
(pfet_m0) Generic                                 1       1           1       1
(subc, -) Generic                                 1       -*          1       -*

Reduce Statistics
=================                               Filtered             Reduced
Cell/Device                               schematic  layout   schematic  layout
(nfet) Generic                                    0       0           0       0
(nfet_m0) Generic                                 1       1           1       1
(pfet) Generic                                    0       0           0       0
(pfet_m0) Generic                                 1       1           1       1
(subc, -) Generic                                 1       -*          1       -*
                                             ------  ------      ------  ------
Total                                             3       2           3       2

###############################################################################
###### XOR2X1 cmos_sch CORELIB  <vs>  XOR2X1 layout CORELIB
###############################################################################
###### This report is for informational purposes only. This cell
###### has been expanded because of a mismatch in reduced instance counts.
###############################################################################

Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(pfet) Generic                                    5       5
(subc) Generic                                    1       0*
(nfet) Generic                                    5       5
                                             ------  ------
Total                                            11      10

Filter Statistics
=================                               Original            Filtered
Cell/Device                               schematic  layout   schematic  layout
(nfet) Generic                                    0       0           0       0
(nfet_m0) Generic                                 5       5           5       5
(pfet) Generic                                    0       0           0       0
(pfet_m0) Generic                                 5       5           5       5
(subc, -) Generic                                 1       -*          1       -*

Reduce Statistics
=================                               Filtered             Reduced
Cell/Device                               schematic  layout   schematic  layout
(nfet) Generic                                    0       0           0       0
(nfet_m0) Generic                                 5       5           5       5
(pfet) Generic                                    0       0           0       0
(pfet_m0) Generic                                 5       5           5       5
(subc, -) Generic                                 1       -*          1       -*
                                             ------  ------      ------  ------
Total                                            11      10          11      10

###############################################################################
###### AO21X3 cmos_sch CORELIB  <vs>  AO21X3 layout CORELIB
###############################################################################
###### This report is for informational purposes only. This cell
###### has been expanded because of a mismatch in reduced instance counts.
###############################################################################

Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(pfet) Generic                                    4       4
(nfet) Generic                                    4       4
(subc) Generic                                    1       0*
                                             ------  ------
Total                                             9       8

Filter Statistics
=================                               Original            Filtered
Cell/Device                               schematic  layout   schematic  layout
(nfet) Generic                                    0       0           0       0
(nfet_m0) Generic                                 4       4           4       4
(pfet) Generic                                    0       0           0       0
(pfet_m0) Generic                                 4       4           4       4
(subc, -) Generic                                 1       -*          1       -*

Reduce Statistics
=================                               Filtered             Reduced
Cell/Device                               schematic  layout   schematic  layout
(nfet) Generic                                    0       0           0       0
(nfet_m0) Generic                                 4       4           4       4
(pfet) Generic                                    0       0           0       0
(pfet_m0) Generic                                 4       4           4       4
(subc, -) Generic                                 1       -*          1       -*
                                             ------  ------      ------  ------
Total                                             9       8           9       8

###############################################################################
###### DFCX3 cmos_sch CORELIB  <vs>  DFCX3 layout CORELIB
###############################################################################
###### This report is for informational purposes only. This cell
###### has been expanded because of unstable instance parameter values.
###############################################################################
   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(subc) Generic                                    1       0*
(nfet) Generic                                   15      15
(pfet) Generic                                   15      15
                                             ------  ------
Total                                            31      30

Filter Statistics
=================                               Original            Filtered
Cell/Device                               schematic  layout   schematic  layout
(nfet) Generic                                    0       0           0       0
(nfet_m0) Generic                                15      15          15      15
(pfet) Generic                                    0       0           0       0
(pfet_m0) Generic                                15      15          15      15
(subc, -) Generic                                 1       -*          1       -*

Reduce Statistics
=================                               Filtered             Reduced
Cell/Device                               schematic  layout   schematic  layout
(nfet) Generic                                    0       0           0       0
(nfet_m0) Generic                                15      15          15      15
(pfet) Generic                                    0       0           0       0
(pfet_m0) Generic                                15      15          15      15
(subc, -) Generic                                 1       -*          1       -*
                                             ------  ------      ------  ------
Total                                            31      30          31      30

###############################################################################
###### DFCX1 cmos_sch CORELIB  <vs>  DFCX1 layout CORELIB
###############################################################################
###### This report is for informational purposes only. This cell
###### has been expanded because of a mismatch in reduced instance counts.
###############################################################################

Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(subc) Generic                                    1       0*
(nfet) Generic                                   15      15
(pfet) Generic                                   15      15
                                             ------  ------
Total                                            31      30

Filter Statistics
=================                               Original            Filtered
Cell/Device                               schematic  layout   schematic  layout
(nfet) Generic                                    0       0           0       0
(nfet_m0) Generic                                15      15          15      15
(pfet) Generic                                    0       0           0       0
(pfet_m0) Generic                                15      15          15      15
(subc, -) Generic                                 1       -*          1       -*

Reduce Statistics
=================                               Filtered             Reduced
Cell/Device                               schematic  layout   schematic  layout
(nfet) Generic                                    0       0           0       0
(nfet_m0) Generic                                15      15          15      15
(pfet) Generic                                    0       0           0       0
(pfet_m0) Generic                                15      15          15      15
(subc, -) Generic                                 1       -*          1       -*
                                             ------  ------      ------  ------
Total                                            31      30          31      30

###############################################################################
###### NOR2XL cmos_sch CORELIB  <vs>  NOR2XL layout CORELIB
###############################################################################
###### This report is for informational purposes only. This cell
###### has been expanded because of unstable instance parameter values.
###############################################################################
   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(pfet) Generic                                    2       2
(nfet) Generic                                    2       2
(subc) Generic                                    1       0*
                                             ------  ------
Total                                             5       4

Filter Statistics
=================                               Original            Filtered
Cell/Device                               schematic  layout   schematic  layout
(nfet) Generic                                    0       0           0       0
(nfet_m0) Generic                                 2       2           2       2
(pfet) Generic                                    0       0           0       0
(pfet_m0) Generic                                 2       2           2       2
(subc, -) Generic                                 1       -*          1       -*

Reduce Statistics
=================                               Filtered             Reduced
Cell/Device                               schematic  layout   schematic  layout
(nfet) Generic                                    0       0           0       0
(nfet_m0) Generic                                 2       2           2       2
(pfet) Generic                                    0       0           0       0
(pfet_m0) Generic                                 2       2           2       2
(subc, -) Generic                                 1       -*          1       -*
                                             ------  ------      ------  ------
Total                                             5       4           5       4

###############################################################################
###### OR2X3 cmos_sch CORELIB  <vs>  OR2X3 layout CORELIB
###############################################################################
###### This report is for informational purposes only. This cell
###### has been expanded because of a mismatch in reduced instance counts.
###############################################################################

Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(pfet) Generic                                    3       3
(nfet) Generic                                    3       3
(subc) Generic                                    1       0*
                                             ------  ------
Total                                             7       6

Filter Statistics
=================                               Original            Filtered
Cell/Device                               schematic  layout   schematic  layout
(nfet) Generic                                    0       0           0       0
(nfet_m0) Generic                                 3       3           3       3
(pfet) Generic                                    0       0           0       0
(pfet_m0) Generic                                 3       3           3       3
(subc, -) Generic                                 1       -*          1       -*

Reduce Statistics
=================                               Filtered             Reduced
Cell/Device                               schematic  layout   schematic  layout
(nfet) Generic                                    0       0           0       0
(nfet_m0) Generic                                 3       3           3       3
(pfet) Generic                                    0       0           0       0
(pfet_m0) Generic                                 3       3           3       3
(subc, -) Generic                                 1       -*          1       -*
                                             ------  ------      ------  ------
Total                                             7       6           7       6

*******************************************************************************
****** spc2 schematic IMP_DIG_SPI  <vs>  spc2 layout IMP_DIG_SPI
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(subc) Generic                                    1       7*
(fillcaps schematic IMP_DIG_SPI, _) Cell          1       0*
(NAND3X1 cmos_sch CORELIB, NAND3X1) Cell          1       1
(DFPX3 cmos_sch CORELIB, DFPX3) Cell              1       1
(INVXL cmos_sch CORELIB, INVXL) Cell              1       1
(XOR2X1 cmos_sch CORELIB, XOR2X1) Cell            3       3
(AO21X3 cmos_sch CORELIB, AO21X3) Cell            1       1
(DFCX3 cmos_sch CORELIB, DFCX3) Cell             16      16
(DFCX1 cmos_sch CORELIB, DFCX1) Cell             20      20
(NOR2XL cmos_sch CORELIB, NOR2XL) Cell            5       5
(OR2X3 cmos_sch CORELIB, OR2X3) Cell              1       1
(FILLCAPX16 cmos_sch CORELIB, FILLCAPX16 layout CORELIB) Cell                 0       8*
(FILLCAPX32 cmos_sch CORELIB, FILLCAPX32 layout CORELIB) Cell                 0       1*
(FILLCAPX4 cmos_sch CORELIB, FILLCAPX4 layout CORELIB) Cell         0      11*
(FILLCAPX8 cmos_sch CORELIB, FILLCAPX8 layout CORELIB) Cell         0      13*
(_, FILLCELLX16 layout CORELIB) Cell              0       5*
(_, FILLCELLX4 layout CORELIB) Cell               0      12*
(_, FILLCELLX8 layout CORELIB) Cell               0      11*
                                             ------  ------
Total                                            51     117

Filter Statistics
=================                               Original            Filtered
Cell/Device                               schematic  layout   schematic  layout
(FILLCAPX16) Cell                                 8       8           8       8
(FILLCAPX32) Cell                                 1       1           1       1
(FILLCAPX4) Cell                                 11      11          11      11
(FILLCAPX8) Cell                                 13      13          13      13
(nfet) Generic                                    0       0           0       0
(nfet_m0) Generic                               591     591         591     591
(pfet) Generic                                    0       0           0       0
(pfet_m0) Generic                               591     591         591     591
(subc) Generic                                   50       7*         50       7*

Reduce Statistics
=================                               Filtered             Reduced
Cell/Device                               schematic  layout   schematic  layout
(FILLCAPX16) Cell                                 8       8           8       8
(FILLCAPX32) Cell                                 1       1           1       1
(FILLCAPX4) Cell                                 11      11          11      11
(FILLCAPX8) Cell                                 13      13          13      13
(nfet) Generic                                    0       0           0       0
(nfet_m0) Generic                               591     591         591     591
(pfet) Generic                                    0       0           0       0
(pfet_m0) Generic                               591     591         591     591
(subc) Generic                                   50       7*          1       1
                                             ------  ------      ------  ------
Total                                          1265    1222        1216    1216

Schematic and Layout Match
