0 0 dataAuditErrors
317 0 GRESDTDI20_REV: ESDTDI20 Revision must be == 3.0 !
320 0 GRESDTDI25_REV: ESDTDI25 Revision must be == 2.0 !
323 0 GRESDFDI25_REV: ESDFDI25 Revision must be == 2.0 !
326 0 GRESDFDI50_REV: ESDFDI50 Revision must be == 2.0 !
329 0 GRESDTDI50_REV: ESDTDI50 Revision must be == 3.0 !
402 0 SBLK without OP
477 0 ESDPDIDN device touching ns pi rn nr pr bb tg ng pc rr rp pd op rxhv sn dp sp
499 0 ESDVPNPNW device touching ns pi rn nr pr bb tg ng pc rr rp pd op rxhv dn sn dp sp
518 0 ESDNDIDN device touching ns pi rn nw nr pr bb tg ng pc bp rr rp pd op rxhv sn dp sp
545 0 ESDNDSX device touching ns pi rn nw nr pr bb tg ng pc bp rr rp pd op rxhv dn sn dp sp
602 0 esdtdi50 anod wiring not allowed through PC !
610 0 esdfdi25/50 anod wiring not allowed through PC !
642 0 ESDFDI device touching ns pi rn nr pr bb tg ng rr rp pd op
657 0 ESDTDI device touching ns pi rn nw nr pr bb tg ng pc rr rp pd op dp
665 0 efuse device without bp
684 0 efuse device touching ns rx pi rn nw nr pr bb tg ng rr rp pd op rxhv dn sn dp sp
764 0 VPNP/VNPN device touching ns pi rn nw nr pr bb tg ng pc rr rp pd op
788 0 High Voltage Resistor device (hvnwres) touching sp,dp
790 0 High Voltage Resistor device (hvpwres) touching sn
830 0 High Voltage Resistor device touching ns pi rn nr pr bb tg ng pc rr rp pd
863 0 HAVAR device touching pi,nw,nr,pr,dg,pc,rr,rp,pd,op
865 0 HAVAR device outside ns or bb
901 0 SBD device must be covered by DN
922 0 SBDI device touching ns pi nw nr pr tg ng pc rr rp op rxhv sn dp sp
946 0 DI Diode device without bp
963 0 DI Diode device touching ns pi rn nr pr bb tg ng pc rr rp pd op rxhv sn dp sp
983 0 DIVPNP device touching ns pi rn nr pr bb tg ng pc rr rp pd op rxhv dn sn dp sp
1027 0 DIPI Diode device touching ns pi rn nr pr bb tg ng pc rr rp pd op rxhv sn dp sp
1029 0 DIPI Diode device touching nw,bp
1091 0 pcapi or pcapim devices touching ns pi rn nr pr bb ng rr rp pd op rxhv sn dp sp
1141 0 mosvar, mosvarm or pcdcapm devices touching ns,jd,pi,rn,nr,pr,dg,bp,rr,rp,pd,op
1190 0 P+ diffusion in ncap nwell found
1216 0 pcdcap devices touching ns pi rn nr pr ng bp rr rp pd op rxhv dn sn dp sp
1581 0 Dual gate poly device without M1/CA connection
1742 0 N+ Diffused Resistor device touching ns,nw,nr,pr
1974 0 FET device touching ns,jd,rn,bb,rr,rp,pd,op
2058 0 FET HV device touching  ns,pi,rn,nr,pr,bb,rr,rp,pd,op
2119 0 Diffused Resistor device touching bb,dg,pc
2217 0 Polysilicon Resistor device touching rx,rn,dg
2223 0 Polysilicon Resistor device not covered by P+ implant
2229 0 Polysilicon Resistor device BB touching pi,ns,nr,pr,dg
2248 0 P Poly resistor RR BB touching pi,ns,nw,nr,pr,dg
2255 0 P Poly resistor RP BB touching pi,ns,nw,nr,pr,dg
2394 0 (AM res) not covered by mask AM
2396 0 (MT res) not covered by mask MT
2398 0 (M4 res) not covered by mask M4
2400 0 (M3 res) not covered by mask M3
2402 0 (M2 res) not covered by mask M2
2404 0 (M1 res) not covered by mask M1
2483 0 Overlapping transmission lines - terminals must abut filters
2526 0 inductor device without bb
2539 0 inductor device touching ns,jd,pi,rn,nw,nr,pr,dg,pc,rr,rp,pd,op
2616 0 M3 and M4 inside enhanced Inductor model must have the same dimension as MT
2620 0 M3/M4 inside standard inductor model is not allowed
2684 0 Missing v2 vias on symind coils between m2 and m3
2686 0 Missing v3 vias on symind coils between m3 and m4
2688 0 Missing v4 vias on symind coils between m4 and mt
2690 0 Missing v2 vias on symind coils between m2 and m3
2692 0 Missing v3 vias on symind coils between m3 and m4
2694 0 Missing v4 vias on symind coils between m4 and mt
2696 0 Missing ft vias on symind coils between mt and am
2698 0 Missing ft vias on symind coils between mt and am
2700 0 Missing ft vias on ind coils between mt and am
2721 0 AM signal wire exiting symetrical inductor straddling metal coil outside the pin
2725 0 Center tap signal wire exiting symetrical inductor outside CT pin
2729 0 Center tap signal wire exiting symetrical inductor outside CT pin
2912 0 AM signal wire not exiting transmission line at port, shorted, or open
2933 0 M4 signal wire not exiting transmission line at port, shorted, or open
2951 0 MT signal wire not exiting transmission line at port, shorted, or open
2975 0 M3 signal wire not exiting transmission line at port, shorted, or open
2996 0 M2 signal wire not exiting transmission line at port, shorted, or open
3142 0 No FT via over HT
3143 0 No FT via over QT
3164 0 MODEL concern - K1 resistor not totally over STI substrate
3168 0 K1 resistor device touching rxhv sn dp sp
3925 0 nw_StampErrorConnect
3929 0 nw_StampErrorFloat
3930 0 nw_StampErrorMult
3933 0 bb_StampErrorConnect
3937 0 bb_StampErrorMult
3940 0 nw_StampErrorConnect
3944 0 nw_StampErrorFloat
3945 0 nw_StampErrorMult
3948 0 sn_StampErrorConnect
3952 0 sn_StampErrorFloat
3953 0 sn_StampErrorMult
3956 0 rn_StampErrorConnect
3960 0 rn_StampErrorFloat
3961 0 rn_StampErrorMult
3964 0 ncap_nw_StampErrorConnect
3968 0 ncap_nw_StampErrorFloat
3969 0 ncap_nw_StampErrorMult
3972 0 DIPI_nw_StampErrorConnect
3976 0 DIPI_nw_StampErrorFloat
3977 0 DIPI_nw_StampErrorMult
3980 0 well_StampErrorConnect
3984 0 well_StampErrorFloat
3985 0 well_StampErrorMult
3988 0 pi_StampErrorConnect
3992 0 pi_StampErrorFloat
3993 0 pi_StampErrorMult
3996 0 dn_StampErrorConnect
4004 0 dn_StampErrorFloat
4006 0 dn_StampErrorMult
4009 0 sbdi_dn_StampErrorConnect
4013 0 sbdi_dn_StampErrorFloat
4015 0 sbdi_dn_StampErrorMult
4018 0 pwell_StampErrorConnect
4022 0 pwell_StampErrorFloat
4023 0 pwell_StampErrorMult
4025 0 substrate_ptap_StampErrorCon
4030 0 substrate_StampErrorCon
4037 0 sub_nti_StampErrorCon
4045 0 Mixed voltage net found : 3V3 or 5V diffusion is connected to 1.8V gate
4050 0 Mixed voltage net found : High Voltage diffusion is connected to Low Voltage gate
4052 0 ptap connected to POWER net found !
4054 0 pwtap connected to POWER net found !
4059 0 forward biased ptie device found ! [tdpdnw/diodepnw] 
4064 0 forward biased ntie device found ! [tdndsx,tdndpw/diodenx,diodendpw] 
4067 0 forward biased pwdn device found ! [wdpwdn / diodepwdn] 
4069 0 NW ring not connected to a power net found !
12141 0 DIODENX device touching ns pi rn nw nr pr bb pc bp rr rp pd dn sn dp sp
12185 0 DIODENDPW device touching rn nw nr pr bb pc bp rp pd sn dp
12226 0 DIODENDPW device touching ns pi rn nw nr pr bb pc bp rr rp pd sn dp
12282 0 DIODENWX device touching ns pi bb dn sn dp sp
12300 0 DIODEDNSX device touching ns pi
12338 0 DIODEPWDN device touching ns pi rn nw bb sn dp sp
12353 0 ###### SIX levels of metal M1-M2-M3-M4-MT-AM #####
13808 0 malformed device vnpn_dev
13809 0 malformed device vpnp_dev
13810 0 malformed device nfet20hs_dev
13811 0 malformed device nfet50hs_dev
13812 0 malformed device nfet20mh_dev
13813 0 malformed device nfeti20h_dev
13814 0 malformed device nfeti20t_dev
13815 0 malformed device nfeti25m_dev
13816 0 malformed device nfeti50h_dev
13817 0 malformed device nfeti50m_dev
13818 0 malformed device nfeti50t_dev
13819 0 malformed device pfet20hs_dev
13820 0 malformed device pfet50hs_dev
13821 0 malformed device pfet20h_dev
13822 0 malformed device pfet20t_dev
13823 0 malformed device pfet25m_dev
13824 0 malformed device pfet50h_dev
13825 0 malformed device pfet50m_dev
13826 0 malformed device pfet50t_dev
13827 0 malformed device nfeti_dn_dev_b
13828 0 malformed device nfet6_dn_dev_b
13829 0 malformed device nfeti_dn_dev
13830 0 malformed device nfet6_dn_dev
13831 0 malformed device nfeti_dn_dev_HVT_b
13832 0 malformed device nfet6_dn_dev_HVT_b
13833 0 malformed device nfeti_dn_dev_HVT
13834 0 malformed device nfet6_dn_dev_HVT
13835 0 malformed device nfeti_dn_dev_TG
13836 0 malformed device nfet6_dn_dev_TG
13837 0 malformed device nfeti_dn_mul
13838 0 malformed device nfet6_dn_mul
13839 0 malformed device nfeti_dn_mul_HVT
13840 0 malformed device nfet6_dn_mul_HVT
13841 0 malformed device nfeti_dn_mul_TG
13842 0 malformed device nfet6_dn_mul_TG
13843 0 malformed device nfet_dev
13844 0 malformed device nfet_dev_b
13845 0 malformed device nfet_mul
13846 0 malformed device nfeti_dev
13847 0 malformed device nfeti_dev_b
13848 0 malformed device nfeti_mul
13849 0 malformed device nfet6_dev
13850 0 malformed device nfet6_mul
13851 0 malformed device nfet_dev_TG
13852 0 malformed device nfet_mul_TG
13853 0 malformed device nfeti_dev_TG
13854 0 malformed device nfeti_mul_TG
13855 0 malformed device nfet6_dev_TG
13856 0 malformed device nfet6_mul_TG
13857 0 malformed device nfet_dev_HVT
13858 0 malformed device nfet_mul_HVT
13859 0 malformed device nfet_dev_HVT_b
13860 0 malformed device nfet_dev_SHVT
13861 0 malformed device nfet_mul_SHVT
13862 0 malformed device nfet_dev_SHVT_b
13863 0 malformed device nfeti_dev_HVT
13864 0 malformed device nfeti_mul_HVT
13865 0 malformed device nfeti_dev_HVT_b
13866 0 malformed device pfeti_dn_dev_b
13867 0 malformed device pfet5_dn_dev_b
13868 0 malformed device pfeti_dn_dev
13869 0 malformed device pfet5_dn_dev
13870 0 malformed device pfeti_dn_mul
13871 0 malformed device pfet5_dn_mul
13872 0 malformed device pfeti_dn_dev_HVT_b
13873 0 malformed device pfet5_dn_dev_HVT_b
13874 0 malformed device pfeti_dn_dev_HVT
13875 0 malformed device pfet5_dn_dev_HVT
13876 0 malformed device pfeti_dn_mul_HVT
13877 0 malformed device pfet5_dn_mul_HVT
13878 0 malformed device pfeti_dn_dev_TG
13879 0 malformed device pfet5_dn_dev_TG
13880 0 malformed device pfeti_dn_mul_TG
13881 0 malformed device pfet5_dn_mul_TG
13882 0 malformed device pfet_dev
13883 0 malformed device pfet_dev_b
13884 0 malformed device pfet_mul
13885 0 malformed device pfet_dev_TG
13886 0 malformed device pfet_mul_TG
13887 0 malformed device pfet_dev_HVT
13888 0 malformed device pfet_dev_HVT_b
13889 0 malformed device pfet_mul_HVT
13890 0 malformed device pfet_dev_SHVT
13891 0 malformed device pfet_dev_SHVT_b
13892 0 malformed device pfet_mul_SHVT
13893 0 malformed device nfRFi_dn_dev
13894 0 malformed device nfRF6_dn_dev
13895 0 malformed device nfRFi_dn_mul
13896 0 malformed device nfRF6_dn_mul
13897 0 malformed device nfRFi_dev
13898 0 malformed device nfRF6_dev
13899 0 malformed device nfRF_dev
13900 0 malformed device nfRFi_mul
13901 0 malformed device nfRF6_mul
13902 0 malformed device nfRF_mul
13903 0 malformed device pfRFi_dn_dev
13904 0 malformed device pfRF5_dn_dev
13905 0 malformed device pfRFi_dn_mul
13906 0 malformed device pfRF5_dn_mul
13907 0 malformed device pfRF_dev
13908 0 malformed device pfRF_mul
13909 0 malformed device SBD
13910 0 malformed device DI_diode
13911 0 malformed device DIPI_diode
13912 0 malformed device DI_VPNP
13913 0 malformed device mosvar_dev
13914 0 malformed device mosvar50_dev
13915 0 malformed device pcdcap50_dev
13916 0 malformed device ncap_dev
13917 0 malformed device pcdcapt_dev
13918 0 malformed device pjfet_dev
13919 0 malformed device rnw6pc_dev_no_bp
13921 0 malformed device res6pc_dev_no_bp
13922 0 malformed device rnw6pc_dev
13924 0 malformed device res6pc_dev
13925 0 malformed device rnw6rr_dev
13927 0 malformed device res6rr_dev
13928 0 malformed device rnw6rp_dev
13930 0 malformed device res6rp_dev
13932 0 malformed device hvnwres_dev
13933 0 malformed device hvpwres_dev
13935 0 malformed device res6n_dev
13936 0 malformed device res6n_3_dev
13937 0 malformed device res6n_5_dev
13938 0 malformed device res6p_dev
13939 0 malformed device res6p_3_dev
13940 0 malformed device res6p_4_dev
13942 0 malformed device res6n_sblk
13943 0 malformed device res6n_3_sblk
13944 0 malformed device res6n_5_sblk
13945 0 malformed device res6p_sblk
13946 0 malformed device res6p_3_sblk
13947 0 malformed device res6p_4_sblk
13948 0 malformed device k1_dev_bb
13950 0 malformed device k1_dev_sx
13951 0 malformed device esdnsh_dev
13952 0 malformed device esdpsh_dev
13953 0 malformed device esdnsh_dev_dn
13954 0 malformed device esdpsh_dev_dn
13955 0 malformed device sub_dev
13957 0 malformed device ntie_device
13958 0 malformed device ptie_device
13959 0 malformed device nwsx_device
13960 0 malformed device ntie_in_sp
13961 0 malformed device dnsx_device
13962 0 malformed device pwdn_device
13963 0 malformed device corrPoint_dev_M2
13964 0 malformed device corrPoint_dev_PD
13965 0 malformed device corrPoint_dev_ND
13966 0 malformed device corrPoint_dev_PC
13967 0 malformed device corrPoint_dev_M1
13968 0 malformed device ESD_pdnw_diode
13969 0 malformed device ESD_pdnw_diode_GR
13970 0 malformed device ESD_ndsx
13971 0 malformed device ESD_ndsx_GR
13972 0 malformed device esdfdi50_dev
13973 0 malformed device esdfdi25_dev
13974 0 malformed device esdtdi25_dev
13975 0 malformed device esdtdi20_dev
13976 0 malformed device esdtdi50_dev
13977 0 malformed device MIMpi
13978 0 malformed device MIMdn
13979 0 malformed device MIMnw
13980 0 malformed device MIMsx
13981 0 malformed device MIMhdpi
13982 0 malformed device MIMhddn
13983 0 malformed device MIMhdnw
13984 0 malformed device MIMhdsx
13985 0 malformed device DUALMIMpi
13986 0 malformed device DUALMIMdn
13987 0 malformed device DUALMIMnw
13988 0 malformed device DUALMIMsx
13989 0 malformed device DUALMIMhdpi
13990 0 malformed device DUALMIMhddn
13991 0 malformed device DUALMIMhdnw
13992 0 malformed device DUALMIMhdsx
13994 0 malformed device vncap_top1
13995 0 malformed device vncap_tnw1
13997 0 malformed device vncap_topt
13998 0 malformed device vncap_tnwt
14000 0 malformed device vncap_top2
14001 0 malformed device vncap_tnw2
14003 0 malformed device vncap_top3
14004 0 malformed device vncap_tnw3
14006 0 malformed device vncap_top4
14007 0 malformed device vncap_tnw4
14009 0 malformed device vncap_top1_hv
14010 0 malformed device vncap_tnw1_hv
14012 0 malformed device vncap_topt_hv
14013 0 malformed device vncap_tnwt_hv
14015 0 malformed device vncap_top2_hv
14016 0 malformed device vncap_tnw2_hv
14018 0 malformed device vncap_top3_hv
14019 0 malformed device vncap_tnw3_hv
14021 0 malformed device vncap_top4_hv
14022 0 malformed device vncap_tnw4_hv
14023 0 malformed device am_transmission
14024 0 malformed device ind2_mtam_m1
14025 0 malformed device ind2_mtam_bb
14026 0 malformed device symind3_amam_bb
14027 0 malformed device symind2_amam_bb
14028 0 malformed device symind3_amam_m1
14029 0 malformed device symind2_amam_m1
14030 0 malformed device padOverDev
14031 0 malformed device bondPpc
14032 0 malformed device bondPm1
14033 0 malformed device bondPbb
14034 0 malformed device efuse
14039 0 malformed device coupledA
14044 0 malformed device singleEndA
14048 0 malformed device coupledT
14052 0 malformed device singleEndT
14055 0 malformed device coupled4
14058 0 malformed device singleEnd4
14060 0 malformed device coupled3
14062 0 malformed device singleEnd3
14063 0 malformed device coupled2
14064 0 malformed device singleEnd2
14065 0 malformed device dio_nsx_dev
14066 0 malformed device dio_ndpw_dev
14067 0 malformed device dio_nsp_dev
14068 0 malformed device dio_pnw_dev
14069 0 malformed device dio_nwx_dev
14070 0 malformed device dio_dnsx_dev
14071 0 malformed device dio_pwdn_dev
15861 0 unstable device for dio_pwdn_dev_Device_284
15862 0 unpreserved device dio_pwdn_dev_Device_284
15863 0 unstable device for dio_dnsx_dev_Device_283
15864 0 unpreserved device dio_dnsx_dev_Device_283
15865 0 unstable device for dio_nwx_dev_Device_282
15866 0 unpreserved device dio_nwx_dev_Device_282
15867 0 unstable device for dio_pnw_dev_Device_281
15868 0 unpreserved device dio_pnw_dev_Device_281
15869 0 unstable device for dio_nsp_dev_Device_280
15870 0 unpreserved device dio_nsp_dev_Device_280
15871 0 unstable device for dio_ndpw_dev_Device_279
15872 0 unpreserved device dio_ndpw_dev_Device_279
15873 0 unstable device for dio_nsx_dev_Device_278
15874 0 unpreserved device dio_nsx_dev_Device_278
15875 0 unstable device for am_RES_min_Device_277
15876 0 unpreserved device am_RES_min_Device_277
15877 0 unstable device for m4_RES_min_Device_276
15878 0 unpreserved device m4_RES_min_Device_276
15879 0 unstable device for m4_RES_min_Device_274
15880 0 unpreserved device m4_RES_min_Device_274
15881 0 unstable device for m3_RES_min_Device_273
15882 0 unpreserved device m3_RES_min_Device_273
15883 0 unstable device for m3_RES_min_Device_271
15884 0 unpreserved device m3_RES_min_Device_271
15885 0 unstable device for m2_RES_min_Device_270
15886 0 unpreserved device m2_RES_min_Device_270
15887 0 unstable device for m2_RES_min_Device_268
15888 0 unpreserved device m2_RES_min_Device_268
15889 0 unstable device for mt_RES_min_Device_267
15890 0 unpreserved device mt_RES_min_Device_267
15891 0 unstable device for mt_RES_min_Device_265
15892 0 unpreserved device mt_RES_min_Device_265
15893 0 unstable device for m1_RES_min_Device_264
15894 0 unpreserved device m1_RES_min_Device_264
15895 0 unstable device for m1_RES_min_Device_262
15896 0 unpreserved device m1_RES_min_Device_262
15897 0 unstable device for singleEnd2_shield1
15898 0 unpreserved device singleEnd2_shield1
15899 0 unstable device for coupled2_shield1
15900 0 unpreserved device coupled2_shield1
15901 0 unstable device for singleEnd3_shield2
15902 0 unpreserved device singleEnd3_shield2
15903 0 unstable device for singleEnd3_shield1
15904 0 unpreserved device singleEnd3_shield1
15905 0 unstable device for coupled3_shield2
15906 0 unpreserved device coupled3_shield2
15907 0 unstable device for coupled3_shield1
15908 0 unpreserved device coupled3_shield1
15909 0 unstable device for singleEnd4_shield3
15910 0 unpreserved device singleEnd4_shield3
15911 0 unstable device for singleEnd4_shield2
15912 0 unpreserved device singleEnd4_shield2
15913 0 unstable device for singleEnd4_shield1
15914 0 unpreserved device singleEnd4_shield1
15915 0 unstable device for coupled4_shield3
15916 0 unpreserved device coupled4_shield3
15917 0 unstable device for coupled4_shield2
15918 0 unpreserved device coupled4_shield2
15919 0 unstable device for coupled4_shield1
15920 0 unpreserved device coupled4_shield1
15921 0 unstable device for singleEndT_shield4
15922 0 unpreserved device singleEndT_shield4
15923 0 unstable device for singleEndT_shield3
15924 0 unpreserved device singleEndT_shield3
15925 0 unstable device for singleEndT_shield2
15926 0 unpreserved device singleEndT_shield2
15927 0 unstable device for singleEndT_shield1
15928 0 unpreserved device singleEndT_shield1
15929 0 unstable device for coupledT_shield4
15930 0 unpreserved device coupledT_shield4
15931 0 unstable device for coupledT_shield3
15932 0 unpreserved device coupledT_shield3
15933 0 unstable device for coupledT_shield2
15934 0 unpreserved device coupledT_shield2
15935 0 unstable device for coupledT_shield1
15936 0 unpreserved device coupledT_shield1
15937 0 unstable device for singleEndA_shieldT
15938 0 unpreserved device singleEndA_shieldT
15939 0 unstable device for singleEndA_shield4
15940 0 unpreserved device singleEndA_shield4
15941 0 unstable device for singleEndA_shield3
15942 0 unpreserved device singleEndA_shield3
15943 0 unstable device for singleEndA_shield2
15944 0 unpreserved device singleEndA_shield2
15945 0 unstable device for singleEndA_shield1
15946 0 unpreserved device singleEndA_shield1
15947 0 unstable device for coupledA_shieldT
15948 0 unpreserved device coupledA_shieldT
15949 0 unstable device for coupledA_shield4
15950 0 unpreserved device coupledA_shield4
15951 0 unstable device for coupledA_shield3
15952 0 unpreserved device coupledA_shield3
15953 0 unstable device for coupledA_shield2
15954 0 unpreserved device coupledA_shield2
15955 0 unstable device for coupledA_shield1
15956 0 unpreserved device coupledA_shield1
15957 0 unstable device for efuse_Device_231
15958 0 unpreserved device efuse_Device_231
15959 0 unstable device for bondPbb_Device_230
15960 0 unpreserved device bondPbb_Device_230
15961 0 unstable device for bondPm1_Device_229
15962 0 unpreserved device bondPm1_Device_229
15963 0 unstable device for bondPpc_Device_228
15964 0 unpreserved device bondPpc_Device_228
15965 0 unstable device for padOverDev_Device_227
15966 0 unpreserved device padOverDev_Device_227
15967 0 unstable device for symind2_amam_m1_Device_226
15968 0 unpreserved device symind2_amam_m1_Device_226
15969 0 unstable device for symind3_amam_m1_Device_225
15970 0 unpreserved device symind3_amam_m1_Device_225
15971 0 unstable device for symind2_amam_bb_Device_224
15972 0 unpreserved device symind2_amam_bb_Device_224
15973 0 unstable device for symind3_amam_bb_Device_223
15974 0 unpreserved device symind3_amam_bb_Device_223
15975 0 unstable device for ind2_mtam_bb_Device_222
15976 0 unpreserved device ind2_mtam_bb_Device_222
15977 0 unstable device for ind2_mtam_m1_Device_221
15978 0 unpreserved device ind2_mtam_m1_Device_221
15979 0 unstable device for am_transmission_Device_220
15980 0 unpreserved device am_transmission_Device_220
15981 0 unstable device for vncap_tnw4_hv_Device_219
15982 0 unpreserved device vncap_tnw4_hv_Device_219
15983 0 unstable device for vncap_top4_hv_pwell
15984 0 unpreserved device vncap_top4_hv_pwell
15985 0 unstable device for vncap_top4_hv_subs
15986 0 unpreserved device vncap_top4_hv_subs
15987 0 unstable device for vncap_tnw3_hv_Device_216
15988 0 unpreserved device vncap_tnw3_hv_Device_216
15989 0 unstable device for vncap_top3_hv_pwell
15990 0 unpreserved device vncap_top3_hv_pwell
15991 0 unstable device for vncap_top3_hv_subs
15992 0 unpreserved device vncap_top3_hv_subs
15993 0 unstable device for vncap_tnw2_hv_Device_213
15994 0 unpreserved device vncap_tnw2_hv_Device_213
15995 0 unstable device for vncap_top2_hv_pwell
15996 0 unpreserved device vncap_top2_hv_pwell
15997 0 unstable device for vncap_top2_hv_subs
15998 0 unpreserved device vncap_top2_hv_subs
15999 0 unstable device for vncap_tnwt_hv_Device_210
16000 0 unpreserved device vncap_tnwt_hv_Device_210
16001 0 unstable device for vncap_topt_hv_pwell
16002 0 unpreserved device vncap_topt_hv_pwell
16003 0 unstable device for vncap_topt_hv_subs
16004 0 unpreserved device vncap_topt_hv_subs
16005 0 unstable device for vncap_tnw1_hv_Device_207
16006 0 unpreserved device vncap_tnw1_hv_Device_207
16007 0 unstable device for vncap_top1_hv_pwell
16008 0 unpreserved device vncap_top1_hv_pwell
16009 0 unstable device for vncap_top1_hv_subs
16010 0 unpreserved device vncap_top1_hv_subs
16011 0 unstable device for vncap_tnw4_Device_204
16012 0 unpreserved device vncap_tnw4_Device_204
16013 0 unstable device for vncap_top4_pwell
16014 0 unpreserved device vncap_top4_pwell
16015 0 unstable device for vncap_top4_subs
16016 0 unpreserved device vncap_top4_subs
16017 0 unstable device for vncap_tnw3_Device_201
16018 0 unpreserved device vncap_tnw3_Device_201
16019 0 unstable device for vncap_top3_pwell
16020 0 unpreserved device vncap_top3_pwell
16021 0 unstable device for vncap_top3_subs
16022 0 unpreserved device vncap_top3_subs
16023 0 unstable device for vncap_tnw2_Device_198
16024 0 unpreserved device vncap_tnw2_Device_198
16025 0 unstable device for vncap_top2_pwell
16026 0 unpreserved device vncap_top2_pwell
16027 0 unstable device for vncap_top2_subs
16028 0 unpreserved device vncap_top2_subs
16029 0 unstable device for vncap_tnwt_Device_195
16030 0 unpreserved device vncap_tnwt_Device_195
16031 0 unstable device for vncap_topt_pwell
16032 0 unpreserved device vncap_topt_pwell
16033 0 unstable device for vncap_topt_subs
16034 0 unpreserved device vncap_topt_subs
16035 0 unstable device for vncap_tnw1_Device_192
16036 0 unpreserved device vncap_tnw1_Device_192
16037 0 unstable device for vncap_top1_pwell
16038 0 unpreserved device vncap_top1_pwell
16039 0 unstable device for vncap_top1_subs
16040 0 unpreserved device vncap_top1_subs
16041 0 unstable device for DUALMIMhdsx_Device_189
16042 0 unpreserved device DUALMIMhdsx_Device_189
16043 0 unstable device for DUALMIMhdnw_Device_188
16044 0 unpreserved device DUALMIMhdnw_Device_188
16045 0 unstable device for DUALMIMhddn_Device_187
16046 0 unpreserved device DUALMIMhddn_Device_187
16047 0 unstable device for DUALMIMhdpi_Device_186
16048 0 unpreserved device DUALMIMhdpi_Device_186
16049 0 unstable device for DUALMIMsx_Device_185
16050 0 unpreserved device DUALMIMsx_Device_185
16051 0 unstable device for DUALMIMnw_Device_184
16052 0 unpreserved device DUALMIMnw_Device_184
16053 0 unstable device for DUALMIMdn_Device_183
16054 0 unpreserved device DUALMIMdn_Device_183
16055 0 unstable device for DUALMIMpi_Device_182
16056 0 unpreserved device DUALMIMpi_Device_182
16057 0 unstable device for MIMhdsx_Device_181
16058 0 unpreserved device MIMhdsx_Device_181
16059 0 unstable device for MIMhdnw_Device_180
16060 0 unpreserved device MIMhdnw_Device_180
16061 0 unstable device for MIMhddn_Device_179
16062 0 unpreserved device MIMhddn_Device_179
16063 0 unstable device for MIMhdpi_Device_178
16064 0 unpreserved device MIMhdpi_Device_178
16065 0 unstable device for MIMsx_Device_177
16066 0 unpreserved device MIMsx_Device_177
16067 0 unstable device for MIMnw_Device_176
16068 0 unpreserved device MIMnw_Device_176
16069 0 unstable device for MIMdn_Device_175
16070 0 unpreserved device MIMdn_Device_175
16071 0 unstable device for MIMpi_Device_174
16072 0 unpreserved device MIMpi_Device_174
16073 0 unstable device for esdtdi50_dev_Device_173
16074 0 unpreserved device esdtdi50_dev_Device_173
16075 0 unstable device for esdtdi20_dev_Device_172
16076 0 unpreserved device esdtdi20_dev_Device_172
16077 0 unstable device for esdtdi25_dev_Device_171
16078 0 unpreserved device esdtdi25_dev_Device_171
16079 0 unstable device for esdfdi25_dev_Device_170
16080 0 unpreserved device esdfdi25_dev_Device_170
16081 0 unstable device for esdfdi50_dev_Device_169
16082 0 unpreserved device esdfdi50_dev_Device_169
16083 0 unstable device for ESD_ndsx_dn_Device_168
16084 0 unpreserved device ESD_ndsx_dn_Device_168
16085 0 unstable device for ESD_ndsx_GR_Device_167
16086 0 unpreserved device ESD_ndsx_GR_Device_167
16087 0 unstable device for ESD_ndsx_Device_166
16088 0 unpreserved device ESD_ndsx_Device_166
16089 0 unstable device for ESD_pdnw_dn_Device_165
16090 0 unpreserved device ESD_pdnw_dn_Device_165
16091 0 unstable device for ESD_pdnw_diode_GR_Device_164
16092 0 unpreserved device ESD_pdnw_diode_GR_Device_164
16093 0 unstable device for ESD_pdnw_diode_Device_163
16094 0 unpreserved device ESD_pdnw_diode_Device_163
16095 0 unstable device for corrPoint_dev_M1_Device_162
16096 0 unpreserved device corrPoint_dev_M1_Device_162
16097 0 unstable device for corrPoint_dev_PC_Device_161
16098 0 unpreserved device corrPoint_dev_PC_Device_161
16099 0 unstable device for corrPoint_dev_ND_Device_160
16100 0 unpreserved device corrPoint_dev_ND_Device_160
16101 0 unstable device for corrPoint_dev_PD_Device_159
16102 0 unpreserved device corrPoint_dev_PD_Device_159
16103 0 unstable device for corrPoint_dev_M2_Device_158
16104 0 unpreserved device corrPoint_dev_M2_Device_158
16105 0 unstable device for pwdn_device_Device_157
16106 0 unpreserved device pwdn_device_Device_157
16107 0 unstable device for dnsx_device_Device_156
16108 0 unpreserved device dnsx_device_Device_156
16109 0 unstable device for ntie_in_sp_Device_155
16110 0 unpreserved device ntie_in_sp_Device_155
16111 0 unstable device for nwsx_device_Device_154
16112 0 unpreserved device nwsx_device_Device_154
16113 0 unstable device for ptie_device_Device_153
16114 0 unpreserved device ptie_device_Device_153
16115 0 unstable device for ntie_device_Device_151
16116 0 unpreserved device ntie_device_Device_151
16117 0 unstable device for ntie_device_Device_152
16118 0 unpreserved device ntie_device_Device_152
16119 0 unstable device for sub_dev_Device_150
16120 0 unpreserved device sub_dev_Device_150
16121 0 unstable device for esdpsh_dev_dn_Device_149
16122 0 unpreserved device esdpsh_dev_dn_Device_149
16123 0 unstable device for esdnsh_dev_dn_Device_148
16124 0 unpreserved device esdnsh_dev_dn_Device_148
16125 0 unstable device for esdpsh_dev_Device_147
16126 0 unpreserved device esdpsh_dev_Device_147
16127 0 unstable device for esdnsh_dev_Device_146
16128 0 unpreserved device esdnsh_dev_Device_146
16129 0 unstable device for k1_dev_sx_pwell
16130 0 unpreserved device k1_dev_sx_pwell
16131 0 unstable device for k1_dev_sx_subs
16132 0 unpreserved device k1_dev_sx_subs
16133 0 unstable device for k1_dev_bb_Device_143
16134 0 unpreserved device k1_dev_bb_Device_143
16135 0 unstable device for res6p_4_sblk_Device_142
16136 0 unpreserved device res6p_4_sblk_Device_142
16137 0 unstable device for res6p_3_sblk_Device_141
16138 0 unpreserved device res6p_3_sblk_Device_141
16139 0 unstable device for res6p_sblk_Device_140
16140 0 unpreserved device res6p_sblk_Device_140
16141 0 unstable device for res6n_5_sblk_Device_139
16142 0 unpreserved device res6n_5_sblk_Device_139
16143 0 unstable device for res6n_3_sblk_Device_138
16144 0 unpreserved device res6n_3_sblk_Device_138
16145 0 unstable device for res6n_sblk_pwell
16146 0 unpreserved device res6n_sblk_pwell
16147 0 unstable device for res6n_sblk_subs
16148 0 unpreserved device res6n_sblk_subs
16149 0 unstable device for res6p_4_dev_Device_135
16150 0 unpreserved device res6p_4_dev_Device_135
16151 0 unstable device for res6p_3_dev_Device_134
16152 0 unpreserved device res6p_3_dev_Device_134
16153 0 unstable device for res6p_dev_Device_133
16154 0 unpreserved device res6p_dev_Device_133
16155 0 unstable device for res6n_5_dev_Device_132
16156 0 unpreserved device res6n_5_dev_Device_132
16157 0 unstable device for res6n_3_dev_Device_131
16158 0 unpreserved device res6n_3_dev_Device_131
16159 0 unstable device for res6n_dev_pwell
16160 0 unpreserved device res6n_dev_pwell
16161 0 unstable device for res6n_dev_subs
16162 0 unpreserved device res6n_dev_subs
16163 0 unstable device for hvpwres_dev_Device_128
16164 0 unpreserved device hvpwres_dev_Device_128
16165 0 unstable device for hvnwres_dev_pwell
16166 0 unpreserved device hvnwres_dev_pwell
16167 0 unstable device for hvnwres_dev_subs
16168 0 unpreserved device hvnwres_dev_subs
16169 0 unstable device for res6rp_dev_pwell
16170 0 unpreserved device res6rp_dev_pwell
16171 0 unstable device for res6rp_dev_subs
16172 0 unpreserved device res6rp_dev_subs
16173 0 unstable device for rnw6rp_dev_Device_123
16174 0 unpreserved device rnw6rp_dev_Device_123
16175 0 unstable device for res6rr_dev_pwell
16176 0 unpreserved device res6rr_dev_pwell
16177 0 unstable device for res6rr_dev_subs
16178 0 unpreserved device res6rr_dev_subs
16179 0 unstable device for rnw6rr_dev_Device_120
16180 0 unpreserved device rnw6rr_dev_Device_120
16181 0 unstable device for res6pc_dev_pwell
16182 0 unpreserved device res6pc_dev_pwell
16183 0 unstable device for res6pc_dev_subs
16184 0 unpreserved device res6pc_dev_subs
16185 0 unstable device for rnw6pc_dev_Device_117
16186 0 unpreserved device rnw6pc_dev_Device_117
16187 0 unstable device for res6pc_dev_no_bp_pwell
16188 0 unpreserved device res6pc_dev_no_bp_pwell
16189 0 unstable device for res6pc_dev_no_bp_subs
16190 0 unpreserved device res6pc_dev_no_bp_subs
16191 0 unstable device for rnw6pc_dev_no_bp_Device_114
16192 0 unpreserved device rnw6pc_dev_no_bp_Device_114
16193 0 unstable device for pjfet_dev_Device_113
16194 0 unpreserved device pjfet_dev_Device_113
16195 0 unstable device for pcap50_dev_Device_112
16196 0 unpreserved device pcap50_dev_Device_112
16197 0 unstable device for pcap_dev_Device_111
16198 0 unpreserved device pcap_dev_Device_111
16199 0 unstable device for pcdcapt_dev_Device_110
16200 0 unpreserved device pcdcapt_dev_Device_110
16201 0 unstable device for ncap_dev_Device_109
16202 0 unpreserved device ncap_dev_Device_109
16203 0 unstable device for pcdcap50_dev_Device_108
16204 0 unpreserved device pcdcap50_dev_Device_108
16205 0 unstable device for mosvar50_dev_Device_107
16206 0 unpreserved device mosvar50_dev_Device_107
16207 0 unstable device for mosvar_dev_Device_106
16208 0 unpreserved device mosvar_dev_Device_106
16209 0 unstable device for DI_VPNP_Device_105
16210 0 unpreserved device DI_VPNP_Device_105
16211 0 unstable device for DIPI_diode_Device_104
16212 0 unpreserved device DIPI_diode_Device_104
16213 0 unstable device for DI_diode_Device_103
16214 0 unpreserved device DI_diode_Device_103
16215 0 unstable device for SBD_Device_102
16216 0 unpreserved device SBD_Device_102
16217 0 unstable device for pfRF_mul_Device_101
16218 0 unpreserved device pfRF_mul_Device_101
16219 0 unstable device for pfRF_dev_Device_100
16220 0 unpreserved device pfRF_dev_Device_100
16221 0 unstable device for pfRF5_dn_mul_Device_99
16222 0 unpreserved device pfRF5_dn_mul_Device_99
16223 0 unstable device for pfRFi_dn_mul_Device_98
16224 0 unpreserved device pfRFi_dn_mul_Device_98
16225 0 unstable device for pfRF5_dn_dev_Device_97
16226 0 unpreserved device pfRF5_dn_dev_Device_97
16227 0 unstable device for pfRFi_dn_dev_Device_96
16228 0 unpreserved device pfRFi_dn_dev_Device_96
16229 0 unstable device for nfRF_mul_Device_95
16230 0 unpreserved device nfRF_mul_Device_95
16231 0 unstable device for nfRF6_mul_Device_94
16232 0 unpreserved device nfRF6_mul_Device_94
16233 0 unstable device for nfRFi_mul_Device_93
16234 0 unpreserved device nfRFi_mul_Device_93
16235 0 unstable device for nfRF_dev_Device_92
16236 0 unpreserved device nfRF_dev_Device_92
16237 0 unstable device for nfRF6_dev_Device_91
16238 0 unpreserved device nfRF6_dev_Device_91
16239 0 unstable device for nfRFi_dev_Device_90
16240 0 unpreserved device nfRFi_dev_Device_90
16241 0 unstable device for nfRF6_dn_mul_Device_89
16242 0 unpreserved device nfRF6_dn_mul_Device_89
16243 0 unstable device for nfRFi_dn_mul_Device_88
16244 0 unpreserved device nfRFi_dn_mul_Device_88
16245 0 unstable device for nfRF6_dn_dev_Device_87
16246 0 unpreserved device nfRF6_dn_dev_Device_87
16247 0 unstable device for nfRFi_dn_dev_Device_86
16248 0 unpreserved device nfRFi_dn_dev_Device_86
16249 0 unstable device for pfet_mul_SHVT_Device_85
16250 0 unpreserved device pfet_mul_SHVT_Device_85
16251 0 unstable device for pfet_dev_SHVT_b_Device_84
16252 0 unpreserved device pfet_dev_SHVT_b_Device_84
16253 0 unstable device for pfet_dev_SHVT_Device_83
16254 0 unpreserved device pfet_dev_SHVT_Device_83
16255 0 unstable device for pfet_mul_HVT_Device_82
16256 0 unpreserved device pfet_mul_HVT_Device_82
16257 0 unstable device for pfet_dev_HVT_b_Device_81
16258 0 unpreserved device pfet_dev_HVT_b_Device_81
16259 0 unstable device for pfet_dev_HVT_Device_80
16260 0 unpreserved device pfet_dev_HVT_Device_80
16261 0 unstable device for pfet_mul_TG_Device_79
16262 0 unpreserved device pfet_mul_TG_Device_79
16263 0 unstable device for pfet_dev_TG_Device_78
16264 0 unpreserved device pfet_dev_TG_Device_78
16265 0 unstable device for pfet_mul_Device_77
16266 0 unpreserved device pfet_mul_Device_77
16267 0 unstable device for pfet_dev_b_Device_76
16268 0 unpreserved device pfet_dev_b_Device_76
16269 0 unstable device for pfet_dev_Device_75
16270 0 unpreserved device pfet_dev_Device_75
16271 0 unstable device for pfet5_dn_mul_TG_Device_74
16272 0 unpreserved device pfet5_dn_mul_TG_Device_74
16273 0 unstable device for pfeti_dn_mul_TG_Device_73
16274 0 unpreserved device pfeti_dn_mul_TG_Device_73
16275 0 unstable device for pfet5_dn_dev_TG_Device_72
16276 0 unpreserved device pfet5_dn_dev_TG_Device_72
16277 0 unstable device for pfeti_dn_dev_TG_Device_71
16278 0 unpreserved device pfeti_dn_dev_TG_Device_71
16279 0 unstable device for pfet5_dn_mul_HVT_Device_70
16280 0 unpreserved device pfet5_dn_mul_HVT_Device_70
16281 0 unstable device for pfeti_dn_mul_HVT_Device_69
16282 0 unpreserved device pfeti_dn_mul_HVT_Device_69
16283 0 unstable device for pfet5_dn_dev_HVT_Device_68
16284 0 unpreserved device pfet5_dn_dev_HVT_Device_68
16285 0 unstable device for pfeti_dn_dev_HVT_Device_67
16286 0 unpreserved device pfeti_dn_dev_HVT_Device_67
16287 0 unstable device for pfet5_dn_dev_HVT_b_Device_66
16288 0 unpreserved device pfet5_dn_dev_HVT_b_Device_66
16289 0 unstable device for pfeti_dn_dev_HVT_b_Device_65
16290 0 unpreserved device pfeti_dn_dev_HVT_b_Device_65
16291 0 unstable device for pfet5_dn_mul_Device_64
16292 0 unpreserved device pfet5_dn_mul_Device_64
16293 0 unstable device for pfeti_dn_mul_Device_63
16294 0 unpreserved device pfeti_dn_mul_Device_63
16295 0 unstable device for pfet5_dn_dev_Device_62
16296 0 unpreserved device pfet5_dn_dev_Device_62
16297 0 unstable device for pfeti_dn_dev_Device_61
16298 0 unpreserved device pfeti_dn_dev_Device_61
16299 0 unstable device for pfet5_dn_dev_b_Device_60
16300 0 unpreserved device pfet5_dn_dev_b_Device_60
16301 0 unstable device for pfeti_dn_dev_b_Device_59
16302 0 unpreserved device pfeti_dn_dev_b_Device_59
16303 0 unstable device for nfeti_dev_HVT_b_Device_58
16304 0 unpreserved device nfeti_dev_HVT_b_Device_58
16305 0 unstable device for nfeti_mul_HVT_Device_57
16306 0 unpreserved device nfeti_mul_HVT_Device_57
16307 0 unstable device for nfeti_dev_HVT_Device_56
16308 0 unpreserved device nfeti_dev_HVT_Device_56
16309 0 unstable device for nfet_dev_SHVT_b_Device_55
16310 0 unpreserved device nfet_dev_SHVT_b_Device_55
16311 0 unstable device for nfet_mul_SHVT_Device_54
16312 0 unpreserved device nfet_mul_SHVT_Device_54
16313 0 unstable device for nfet_dev_SHVT_Device_53
16314 0 unpreserved device nfet_dev_SHVT_Device_53
16315 0 unstable device for nfet_dev_HVT_b_Device_52
16316 0 unpreserved device nfet_dev_HVT_b_Device_52
16317 0 unstable device for nfet_mul_HVT_Device_51
16318 0 unpreserved device nfet_mul_HVT_Device_51
16319 0 unstable device for nfet_dev_HVT_Device_50
16320 0 unpreserved device nfet_dev_HVT_Device_50
16321 0 unstable device for nfet6_mul_TG_Device_49
16322 0 unpreserved device nfet6_mul_TG_Device_49
16323 0 unstable device for nfet6_dev_TG_Device_48
16324 0 unpreserved device nfet6_dev_TG_Device_48
16325 0 unstable device for nfeti_mul_TG_Device_47
16326 0 unpreserved device nfeti_mul_TG_Device_47
16327 0 unstable device for nfeti_dev_TG_Device_46
16328 0 unpreserved device nfeti_dev_TG_Device_46
16329 0 unstable device for nfet_mul_TG_Device_45
16330 0 unpreserved device nfet_mul_TG_Device_45
16331 0 unstable device for nfet_dev_TG_Device_44
16332 0 unpreserved device nfet_dev_TG_Device_44
16333 0 unstable device for nfet6_mul_Device_43
16334 0 unpreserved device nfet6_mul_Device_43
16335 0 unstable device for nfet6_dev_Device_42
16336 0 unpreserved device nfet6_dev_Device_42
16337 0 unstable device for nfeti_mul_Device_41
16338 0 unpreserved device nfeti_mul_Device_41
16339 0 unstable device for nfeti_dev_b_Device_40
16340 0 unpreserved device nfeti_dev_b_Device_40
16341 0 unstable device for nfeti_dev_Device_39
16342 0 unpreserved device nfeti_dev_Device_39
16343 0 unstable device for nfet_mul_Device_38
16344 0 unpreserved device nfet_mul_Device_38
16345 0 unstable device for nfet_dev_b_Device_37
16346 0 unpreserved device nfet_dev_b_Device_37
16347 0 unstable device for nfet_dev_Device_36
16348 0 unpreserved device nfet_dev_Device_36
16349 0 unstable device for nfet6_dn_mul_TG_Device_35
16350 0 unpreserved device nfet6_dn_mul_TG_Device_35
16351 0 unstable device for nfeti_dn_mul_TG_Device_34
16352 0 unpreserved device nfeti_dn_mul_TG_Device_34
16353 0 unstable device for nfet6_dn_mul_HVT_Device_33
16354 0 unpreserved device nfet6_dn_mul_HVT_Device_33
16355 0 unstable device for nfeti_dn_mul_HVT_Device_32
16356 0 unpreserved device nfeti_dn_mul_HVT_Device_32
16357 0 unstable device for nfet6_dn_mul_Device_31
16358 0 unpreserved device nfet6_dn_mul_Device_31
16359 0 unstable device for nfeti_dn_mul_Device_30
16360 0 unpreserved device nfeti_dn_mul_Device_30
16361 0 unstable device for nfet6_dn_dev_TG_Device_29
16362 0 unpreserved device nfet6_dn_dev_TG_Device_29
16363 0 unstable device for nfeti_dn_dev_TG_Device_28
16364 0 unpreserved device nfeti_dn_dev_TG_Device_28
16365 0 unstable device for nfet6_dn_dev_HVT_Device_27
16366 0 unpreserved device nfet6_dn_dev_HVT_Device_27
16367 0 unstable device for nfeti_dn_dev_HVT_Device_26
16368 0 unpreserved device nfeti_dn_dev_HVT_Device_26
16369 0 unstable device for nfet6_dn_dev_HVT_b_Device_25
16370 0 unpreserved device nfet6_dn_dev_HVT_b_Device_25
16371 0 unstable device for nfeti_dn_dev_HVT_b_Device_24
16372 0 unpreserved device nfeti_dn_dev_HVT_b_Device_24
16373 0 unstable device for nfet6_dn_dev_Device_23
16374 0 unpreserved device nfet6_dn_dev_Device_23
16375 0 unstable device for nfeti_dn_dev_Device_22
16376 0 unpreserved device nfeti_dn_dev_Device_22
16377 0 unstable device for nfet6_dn_dev_b_Device_21
16378 0 unpreserved device nfet6_dn_dev_b_Device_21
16379 0 unstable device for nfeti_dn_dev_b_Device_20
16380 0 unpreserved device nfeti_dn_dev_b_Device_20
16381 0 unstable device for pfet50t_dev_Device_19
16382 0 unpreserved device pfet50t_dev_Device_19
16383 0 unstable device for pfet50m_dev_Device_18
16384 0 unpreserved device pfet50m_dev_Device_18
16385 0 unstable device for pfet50h_dev_Device_17
16386 0 unpreserved device pfet50h_dev_Device_17
16387 0 unstable device for pfet25m_dev_Device_16
16388 0 unpreserved device pfet25m_dev_Device_16
16389 0 unstable device for pfet20t_dev_Device_15
16390 0 unpreserved device pfet20t_dev_Device_15
16391 0 unstable device for pfet20h_dev_Device_14
16392 0 unpreserved device pfet20h_dev_Device_14
16393 0 unstable device for pfet50hs_dev_Device_13
16394 0 unpreserved device pfet50hs_dev_Device_13
16395 0 unstable device for pfet20hs_dev_Device_12
16396 0 unpreserved device pfet20hs_dev_Device_12
16397 0 unstable device for nfeti50t_dev_Device_11
16398 0 unpreserved device nfeti50t_dev_Device_11
16399 0 unstable device for nfeti50m_dev_Device_10
16400 0 unpreserved device nfeti50m_dev_Device_10
16401 0 unstable device for nfeti50h_dev_Device_9
16402 0 unpreserved device nfeti50h_dev_Device_9
16403 0 unstable device for nfeti25m_dev_Device_8
16404 0 unpreserved device nfeti25m_dev_Device_8
16405 0 unstable device for nfeti20t_dev_Device_7
16406 0 unpreserved device nfeti20t_dev_Device_7
16407 0 unstable device for nfeti20h_dev_Device_6
16408 0 unpreserved device nfeti20h_dev_Device_6
16409 0 unstable device for nfet20mh_dev_Device_5
16410 0 unpreserved device nfet20mh_dev_Device_5
16411 0 unstable device for nfet50hs_dev_Device_4
16412 0 unpreserved device nfet50hs_dev_Device_4
16413 0 unstable device for nfet20hs_dev_Device_3
16414 0 unpreserved device nfet20hs_dev_Device_3
16415 0 unstable device for vpnp_dev_Device_2
16416 0 unpreserved device vpnp_dev_Device_2
16417 0 unstable device for vnpn_dev_Device_1
16418 0 unpreserved device vnpn_dev_Device_1
